name: Build Docs
on:
  workflow_dispatch:  # manual trigger to kick off workflow
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout iblenv doc build branch
        uses: actions/checkout@v3
        with:
          ref: build_docs_in_ci  # TODO: Change this for production

      - name: Checkout ibllib doc build branch
        uses: actions/checkout@v3
        with:
          repository: int-brain-lab/ibllib
          ref: GC_Doc
          path: ibllib-repo

      - name: Move ibllib up a directory
        run: |
          pwd
          ls -l
          mv ibllib-repo ..

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install docs requirements
        run: |
          sudo apt-get install -y pandoc
          pip install -r docs_gh_pages/requirements-docs.txt
          pip install -e ../ibllib-repo
          jupyter nbextension enable --py --sys-prefix ipyevents

      - name: ONE setup and build docs
        run: |
          python docs_gh_pages/scripts/one_setup.py
          python docs_gh_pages/make_script.py -d
          ls -l docs_gh_pages/_build

# run documentation scripts
# zip up results
# upload results as an artifact
